<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
    <PackageVersion Include="System.Security.Cryptography.Pkcs" Version="10.0.12" />
    <PackageVersion Include="System.Text.Encoding.CodePages" Version="10.0.12" />
    <!-- Packaging & Tooling Dependencies -->
    <PackageVersion Include="MinVer" Version="8.0.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <!-- Test Dependencies -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.31" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.20" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0' Or '$(TargetFramework)' == ''">
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
  </ItemGroup>
</Project>